
services:
  payload:
    image: node:22-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    # pnpmを使用するようにコマンドを変更
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - postgres
    environment:
      DATABASE_URI: postgres://payload:payload_password@postgres:5432/payload
      PORT: 3000
      PAYLOAD_SECRET: your_secret_key_here

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload_password

volumes:
  postgres_data: